### ISSUE TITLE
Improperly formated .csv

### ISSUE THREAD

**Issue by DBrenchley** [washingtonpost/data-police-shootings#1]
Your download is an XML doc .. not a .csv doc ..
Please address .. the data is of import and worthwhile but of little use to many in it's current format

**Comment by kostasx** [comment]
@DBrenchley the file is a properly formatted CSV. What software are you using to open the file?

**Comment by DBrenchley** [comment]
MS Excel 2003 .. negative .. the doc is an xml formatted doc for ver of Office > 2003 ..
If an application cannot parse the xml it cannot be opened .. save it as a .csv doc for an earlier ver of office then any application that supports .csv can open it

**Comment by kostasx** [comment]
Maybe I am missing something here, but there is not doc file in this repository.
There is only a file (with a .csv extension), which is actually a simple text file with comma separated values and that's what makes it a CSV. I am not aware how MS Excel 2003 handles CSV text file importing but I am using LibreOffice, which opens the file without any problem and from there on it can be exported to whatever format you like. Maybe you can try installing LibreOffice  (free and open source) and opening the file there.

**Comment by DBrenchley** [comment]
Have one of your co workers or friends w/ excel open the doc .. I am QUITE
computer literate (though I am occasionally wrong) .. this is XML
I downloaded the .csv .. when opened w/ Excel 2003 I get an XML "tree" ..
not a worksheet
to double check I opened it w/ a text editor .. where I should see ..
value,value,value .. I see <value> <value> etc .. XML
If Libre presents option of saving to office .csv .. that would be your
best bet
Libre will open the doc properly .. because it understands the formatting ..

don't mean to hammer you .. but the data is too worthwhile

**Comment by kostasx** [comment]
Sorry, but I cannot be of any more help here. I am opening the .csv file using Windows notepad and I get a plain text file (See attached image). The `fatal-police-shootings-data.csv` file is definitely not an XML. I suggest you either follow the guide I've posted or use LibreOffice for opening the file. Good luck.
![notepad](https://cloud.githubusercontent.com/assets/1638325/16622442/82c65bc2-439a-11e6-9b53-1db74b23b47b.jpg)

**Comment by DBrenchley** [comment]
we're both correct .. it's a github issue ..
if you download the zip .. it's properly formatted ..
if you right click the fatal-police-shootings-data.csv and save the file .. it's xml ..
apologies .. got what I need .. TY

**Comment by matthewslaney** [comment]
The issue isn't with Github; it's an issue with how you're attempting to use it. It is not designed for you to be able to download individual source files through the web interface. You need to download the zip or use a git agent to clone the repository.

Right click and save does exactly what it's supposed to do: It saves the Github web page at that URL.

**Comment by DBrenchley** [comment]
TY ..  understood ..
