### ISSUE TITLE
Bodycam == Tasercam

### ISSUE THREAD

**Issue by BiTinerary** [washingtonpost/data-police-shootings#11]
I noticed in David Kassick's case. Bodycam technically is False. However the encounter was recorded on a Taser cam. Perhaps body cam should be less specific to include other police recording devices? ie Dash cam, etc...? Or include other columns to pertain to that piece of info?

I like the specificity of Bodycam, especially as more and more departments are beginning to use them. However, I feel like the knowledge or evidence that it implies is equally true in the case of a taser cam. 

Didn't even know that was a thing til I saw David Kassick's vid.
https://www.youtube.com/watch?v=jP-xXO1vuaw

**Comment by jmuyskens** [comment]
You are correct. This is captured in another column in our internal database that we have not yet made public. We will consider adding that in the future. Thank you!
