### ISSUE TITLE
Data entry

### ISSUE THREAD

**Issue by teeCdee** [washingtonpost/data-police-shootings#12]
Noticed there are 46 rows where the victims name is listed as 'TK TK'. Is there a reason for this?

**Comment by drassi** [comment]
TK is like the journalist version of To Be Determined. It's being used as a marker for an unknown person's name here- if you look at the website, the entries with "TK TK" in the source data correspond to "An unidentified person" listed on the website.
![screen shot 2017-08-15 at 1 36 40 am](https://user-images.githubusercontent.com/129646/29303368-486e931e-815a-11e7-8e9a-24c2dadc3559.png)

**Comment by teeCdee** [comment]
Thank you
