### ISSUE TITLE
Body Camera Variable Definition

### ISSUE THREAD

**Issue by rmays1** [washingtonpost/data-police-shootings#13]
I really like this data set, I do however have a question regarding the body cam variable, I cannot locate a code book for it. How is False and True determined? For instance, when you put 'false' is it a definite they did not have it on, or is it possible it is not known? Also case 1399 is labeled as "Not f" which does not align with the rest of the cases.

**Comment by bfeldman89** [comment]
Good question. I actually used their online form this week to let them know that there are confirmed reports that body cam footage of an incident was recorded but their database has marked that variable false. I assumed it was a mistake or just outdated, but maybe this aspect of their methodology is different than I assumed.
