### ISSUE TITLE
id #1591

### ISSUE THREAD

**Issue by jnixy** [washingtonpost/data-police-shootings#16]
This case is always off by one column when I download the data, because there is a quotation mark ahead of the victim's name (Hubert Thomas Byrnes, Jr.).

**Comment by benwiley4000** [comment]
I was going to report this same issue, but I did some research and it seems like quotation marks for entries containing commas is pretty standard CSV practice. Perhaps the CSV parser you're using should be patched? Which one is it?

**Comment by jmuyskens** [comment]
As @benwiley4000 noted, strings containing commas are quoted which is standard practice. This file should be parsed correctly by the major CSV parsers. Excel is able to open the file properly.
