### ISSUE TITLE
What is name TK TK?

### ISSUE THREAD

**Issue by mikekeith52** [washingtonpost/data-police-shootings#19]
Some of the names in the dataset are TK TK. What does this mean?

**Comment by bfeldman89** [comment]
"’To come’ is a printing and journalism reference, commonly abbreviated to ‘TK’. It is used to signify that additional material will be added at a later date.” https://en.wikipedia.org/wiki/To_come_(publishing)

**Comment by jmuyskens** [comment]
@bfeldman89 is correct, we used "TK TK" when the victim name was unknown. I should have explained that in the documentation; however, to make this column more consistent with the others I have changed the output to leave this column blank when the victim name is unknown.
