### ISSUE TITLE
Text summaries

### ISSUE THREAD

**Issue by jellis18** [washingtonpost/data-police-shootings#2]
Is there any way to include a text summary with each case as is shown on the website? Something like this would be great for trying to indicate justification.

**Comment by igorbrigadir** [comment]
I noticed there's far more info (including the descriptions) in https://s3.amazonaws.com/postgraphics/policeshootings/policeshootings2015.json & https://s3.amazonaws.com/postgraphics/policeshootings/policeshootings2016.json maybe those should be included in the repo together with the summary csv

**Comment by BiTinerary** [comment]
Wow... I feel useless.
https://github.com/BiTinerary/anEmptyKitchenChair
