### ISSUE TITLE
Typo in ID 5536

### ISSUE THREAD

**Issue by tpayne9** [washingtonpost/data-police-shootings#21]
The city name in id 5536 should be "Anchorage" not "Achorage"

**Comment by angelakdang** [comment]
@wapo-police-shootings-bot Who is responsible for approving PRs? This one is a no brainer.

**Comment by JohnDovey** [comment]
https://github.com/washingtonpost/data-police-shootings/pull/22/commits

**Comment by jmuyskens** [comment]
Thanks @tpayne9 for raising this. This has been corrected in our internal database and fixed here: https://github.com/washingtonpost/data-police-shootings/commit/b3ebc7cdd68fc33cc72d5d514e78a568b12ec37f#diff-69d9e4a7f4b9fc3e084de6beaa92e12eL5064

Please note that fatal-police-shootings-data.csv is generated by our internal database, so any fixes need to be made upstream and we won't merge PRs for it.
