### ISSUE TITLE
ID 4803 Kevin Pudlik

### ISSUE THREAD

**Issue by NittanyLion1989** [washingtonpost/data-police-shootings#24]
Need to verify if the race of this individual

**Comment by codybarr** [comment]
Fixed in #38.

**Comment by jmuyskens** [comment]
This is now fixed https://github.com/washingtonpost/data-police-shootings/commit/46cdc12da52d19d10538809c440f26ca0bf8e627#diff-dd37f7380c841efc124d6ed1d0fee17972c93e2ec144a3507a044f17f44880b7R4339

**Comment by NittanyLion1989** [comment]
Many thanks for your time and efforts to make the correction.
