### ISSUE TITLE
George Floyd missing from dataset

### ISSUE THREAD

**Issue by brookewenig** [washingtonpost/data-police-shootings#31]
George Floyd is missing from the dataset.

**Comment by theunderhillaccount** [comment]
No, he's not "missing". Please read how the data was compiled and what the inclusion criteria were.

**Comment by bfeldman89** [comment]
> George Floyd is missing from the dataset.

Not really. 

![image](https://user-images.githubusercontent.com/26087892/88886150-78192180-d1ff-11ea-8080-f639c6dc62b7.jpeg)

However, you should check out [Mapping Police Violence](https://mappingpoliceviolence.org/) for data on fatal law enforcement encounters irrespective of whether the LEO used a firearm.

**Comment by brookewenig** [comment]
Great! Sorry, I forgot it was just fatal shootings (not all fatalities).
