### ISSUE TITLE
Use Sex instead of Gender

### ISSUE THREAD

**Issue by LowlyDBA** [washingtonpost/data-police-shootings#33]
The data attribute originally referred to as Gender seems to actually indicate Sex, as it only has the options of M/F/NULL.

Switching the label to Sex would better adhere to the [ISO/IEC 5218](https://en.wikipedia.org/wiki/ISO/IEC_5218) standard for representing human sexes based on the actual data.

**Comment by jmuyskens** [comment]
The Post identifies victims by the gender they identify with if reports indicate that it differs from their biological sex. I've updated the data dictionary to make this explicit.
