### ISSUE TITLE
Gather data on all police shootings, not just fatalities.

### ISSUE THREAD

**Issue by danhanks** [washingtonpost/data-police-shootings#34]
Would be a much larger task, but I think it would be valuable data. We're not seeing the whole picture if we focus only on fatalities. The difference between fatal or non-fatal may a millimeter. If we want to understand why and under what circumstances police are drawing their weapons and firing, we're only looking at a portion of the applicable data.

**Comment by jmuyskens** [comment]
There have been excellent investigations that look at all shootings in a particular area, for instance, [Why Cops Shoot](https://projects.tampabay.com/projects/2017/investigations/florida-police-shootings/) from the Tampa Bay Times. But that project required asking each police department in the state for their records. This would likely not be feasible to do in real time, or on a national level.

We have no plans to change the methodology of our project at this time.
