### ISSUE TITLE
Misspelling of Megan Hockaday

### ISSUE THREAD

**Issue by henrywu2** [washingtonpost/data-police-shootings#39]
Hello,

I believe that "Megan Hockaday", ID 245, is more commonly spelled as "Meagan Hockaday" (see the Wikipedia [page](https://en.wikipedia.org/wiki/Shooting_of_Meagan_Hockaday)). Thanks.

**Comment by jmuyskens** [comment]
This is now fixed https://github.com/washingtonpost/data-police-shootings/commit/46cdc12da52d19d10538809c440f26ca0bf8e627#diff-dd37f7380c841efc124d6ed1d0fee17972c93e2ec144a3507a044f17f44880b7R233
