### ISSUE TITLE
I wrote an iOS app using your data. See your email Washington Post People.

### ISSUE THREAD

**Issue by qed007** [washingtonpost/data-police-shootings#40]
When human is a Junior, do not use a comma. It messes up my parsing.

I want to work with you on this. 
You should want to work with me on this.

**Comment by osoleve** [comment]
I just checked, when ", Jr." appears in the name field, the whole field is surrounded by quotes as is standard to allow the CSV to be parsed as normal. Not sure why your app has a problem with it, but if you ask for help I'm sure someone can assist in figuring it out.

**Comment by qed007** [comment]
4778,"Vincense Williams, Jr.",2019-06-10,shot,gun,24,M,B,Oklahoma City,OK,False,other,Not fleeing,True,,,True

**Comment by jmuyskens** [comment]
Enclosing a field in double quotes is compliant with [RFC 4180](https://tools.ietf.org/html/rfc4180).
