### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by evangambit** [washingtonpost/data-police-shootings#41]
I sent an email August of last year to policeshootingsfeedback@washpost.com and haven't heard back, so I'm making an issue here:

1. The dataset claims that Eduardo Navarrete was shot on 2017-08-12 in Frederickstown, WA.  I believe this is a typo, and the location should be Frederickson, WA.  According to [this](https://patch.com/washington/puyallup/pierce-county-deputies-justified-shooting-man-11-times-report) article the shooting happened in Pierce County on 189th St. Court East, which is presumably [here](https://www.google.com/maps/place/189th+St+Ct+E,+Washington+98375/@47.0841756,-122.3267252,17z/data=!3m1!4b1!4m5!3m4!1s0x54911d4f21e06ddd:0x5d272ecfb108d970!8m2!3d47.0841756!4d-122.3245365) 

2. (new)  Line 5873 has "Bewster County,TX" and should be "Brewster County, TX"

**Comment by jmuyskens** [comment]
Thank you. These have been fixed now.
