### ISSUE TITLE
Please include other killing methods

### ISSUE THREAD

**Issue by mdxe** [washingtonpost/data-police-shootings#43]
like chokings, etc...

**Comment by jmuyskens** [comment]
This project's methodology explicitly excludes those killings and we aren't revisiting that at this time, sorry.

> The Post is documenting only those shootings in which a police officer, in the line of duty, shoots and kills a civilian — the circumstances that most closely parallel the 2014 killing of Michael Brown in Ferguson, Mo., which began the protest movement culminating in Black Lives Matter and an increased focus on police accountability nationwide. The Post is not tracking deaths of people in police custody, fatal shootings by off-duty officers or non-shooting deaths.
