### ISSUE TITLE
about the item "manner_of_death"

### ISSUE THREAD

**Issue by caiyishu** [washingtonpost/data-police-shootings#44]
Thanks for providing us such comprehensive data!
According to the README doc, "the Post is documenting only those shootings in which a police officer, in the line of duty, shoots and kills a civilian."
However, the item "manner_of_death" is of two values, "shot" and "shot and Tasered." Could you clarify the differences between these two? And is it means that the shotted was not necessarily killed?

**Comment by jmuyskens** [comment]
Every entry in the data represents a fatal shooting. "shot and Tasered" means that a police officer also used a stun gun on the victim in the same incident where they were shot and killed with a conventional gun.
