### ISSUE TITLE
timezone on `date` column

### ISSUE THREAD

**Issue by dmil** [washingtonpost/data-police-shootings#45]
Hello! I noticed Breonna Taylor's death is listed on March 12th, but [news reports](https://www.nytimes.com/article/breonna-taylor-police.html) seem to say she was killed shortly after midnight on March 13th. I'm just wondering if the `date` column is being reported out from a certain timezone or if all the dates are based on local time. If it is in a particular timezone, I figured that could be added to the README. Thanks!

**Comment by jmuyskens** [comment]
Thanks, we have now corrected the date to the 12th.
