### ISSUE TITLE
Missing color information on recent data

### ISSUE THREAD

**Issue by lflucasferreira** [washingtonpost/data-police-shootings#46]
I would like to know why there is no information about a lot of lines without color information. Is it just because they are all white people? I hope this is not the case because my Machine Learning analysis shows that more than 50% of killed people are white, and 26% are black people.

**Comment by jmuyskens** [comment]
In general, more details about any given individual are reported over time so more recent cases are more likely to be missing data. If you find any additional information about a person in the database or have further questions about the data collection methodology please email policeshootingsfeedback@washpost.com.
